sudo: required
dist: bionic
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
script:
- export DOCKER_CLI_EXPERIMENTAL=enabled
- source sha_function.sh
- flag_alpine=$(is_base "treehouses/alpine:latest" "kaiyfan/webssh:latest")
- echo $flag_alpine
- echo $DOCKERAPIKEY | docker login -u "kaiyfan" --password-stdin
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- "./docker-build.sh treehouses/alpine:latest arm"
- "./docker-build.sh treehouses/alpine:latest amd64"
- "./docker-build.sh treehouses/alpine:latest arm64"
- flag=$(is_base "treehouses/alpine:latest" "kaiyfan/webssh:latest")
- echo $flag
before_deploy:
- tag_time=$(date +%Y%m%d%H%M)
- echo $tag_time
- tag_latest="latest"
- tag_time=$timetag
- echo $tag_time
- create_manifest kaiyfan/webssh $tag_latest $tag_time kaiyfan/webssh-tags:arm kaiyfan/webssh-tags:amd64 kaiyfan/webssh-tags:arm64
- docker manifest inspect kaiyfan/webssh:$tag_latest
- docker manifest inspect kaiyfan/webssh:$tag_time
deploy:
- provider: script
  script: docker manifest push kaiyfan/webssh:$tag_latest; docker manifest push kaiyfan/webssh:$tag_time
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$flag = true"
env:
  global:
    secure: KEs+0Sx1Xi9aWbYY3/IqGFtSND7yyK370KiW8KJEavuPMQNhf0IiuFXs4DEKVOnleLf0Cc6a5b5PVJKB9P9Ck8IkJp2KKJaEnBtcQAvW+bULKJeEpQs9muIbaDJRyFyBPrJaSfp7l+pFACWPqAkUvghcGWmKohJ/g0K+MICuK2s9GhC+E8EzRYFsrVp7iEfB6zDo3l37nPFh+3Xi3qgagH7/QxxYWGewCp57NW0nUarG6+smT/jA6EvWjfJHFNzUxPtwHhaVcPmIpTSSN9AotKh6mILf2UFC5rdSM/gcBc2L1aaPIhRSg65gNf86VtFWyy9snawfb8+UntaG/mF2Hywr/HshwgufebrfOlzVMp/PW2ohWZ928vCabhWLTBaQL9cINH8zwq1lv34Vn2lPyhNFi0CwY58ZM5Qbw97dgcM7hPOAdsLBvWLoDZpUBXvXIuorEQx343KxKyGSQs0jGrNbbnaTJzq3LUQBSM4Jnt28RBcYf1JyrHP+zvm15NaFqgDBmtQEyYx00It4x47aIqsNIvuS6jEDdYYdHr2//JbU9HJLPASULYXLd58cfZwHuor6Dp1MSv8fsGZMRPlIvpwV8XnUBgqdlHq6afSY0+UGVpYgnQYYhiV8R+UA8wlkLloFBfWR+GOhRhOe+y9KLZGMWcdigHR6w03otU8tLPc=
