sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
script:
- export DOCKER_CLI_EXPERIMENTAL=enabled
- source sha_function.sh
- flag_alpine=$(is_base "treehouses/alpine:latest" "kaiyfan/webssh:latest")
- echo $flag_alpine
#- echo "$DOCKER_PASSWORD" | docker login -u "kaiyfan" --password-stdin
- docker login -u kaiyfan -p $DOCKER_PASSWORD
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- "./docker-build.sh treehouses/alpine:latest arm"
- flag=$(compare "treehouses/alpine:latest" "kaiyfan/webssh:latest")
- echo $flag
before_deploy:
- tag_time=$(date +%Y%m%d%H%M)
- echo $tag_time
- tag_latest="latest"
- tag_time=$timetag
- echo $tag_time
- create_manifest kaiyfan/webssh $tag1 $tag2 kaiyfan/webssh-tags:arm
- docker manifest inspect kaiyfan/webssh:$tag_latest
- docker manifest inspect kaiyfan/webssh:$tag_time
deploy:
- provider: script
  script: docker manifest push kaiyfan/webssh:$tag_latest; docker manifest push kaiyfan/webssh:$tag_time
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$flag = true"
env:
  global:
  - secure: rdlc3abBvXmz9KwYDzaooYf+95xwN4Ep96ZA9zuvdWoih77jrfvgkbHzM8YB/UDdRkMdMSgHPsB6RYaKC+I2zhUDQMDv8pnr5fSlCcxu14sLnxzM8TcXDKzUptZIFwIpNLQU3WN463JRN7N0RMb132VbnVmkvQouuLi/cLvTo93CzZ9/nCuuvwTwoeqYR/JNSPuqEHJfdBXHjKfosnllNpo4Vafg8Rzi6o8X+VlVGLSH8zaylumkELRTjjGBFiD/QLmLhQaKPDfdPAqUs9JNRsa8uJJHN1sKTKX65WnuhJ4BCcOGB/ceGqTxiqUYR5rySloMkU66vgrteB+3plJjJ5Ik6QzgwqHvQ4LaJfaQmZRAjLcBsvfYxDOrMJ6HFwu4lHLaJdPEaLlk0PvH0JiBRbv+qf4ss6sjuHbvATIjxKHnQrJZT+zPe6KwS50DDz/xbRM8chWJ/JTytJDgzEr6phZ0FqFwL9J+OVogeO0wlP9jnrLJAuya3exqJuHDnhoaW2wNyjFo1vxfMXMti8vCpyAQV9u7wglv7pdONix+TOUisV0lxxfCO7pWB7FP1/uV7aYWd8WWuVeqYM7fo9hCa51C/0tTlcANtEx2EsTX1429/1gBqdqEDlNbpWUn2n+yz7kKwtiERFUwtiBwxfLjKVoTColkdJEjyP/U3N+mc20=
  - secure: MftPKgp7uDog84CoEKK7pIhIumdnxj+k/Pem2o+yEFMy+ufrbbWgJ9aHYYuWzgx4UgpbVUao847hNZFkRFqW+V6o3gpSP0p+pLlHSpCKqwrGsZUFSRT4Zb3G+8OJWQ9vu/enUVifuCEVQ3Zr28qGsP6lCis+gqR+44PNqcqNvcFHjs34d2GqKfD9AkMUuvN97akDcwybg8g/4wOTvyAt7ek7Nd9LACuWk0yWYhJIcC1JRaJLmhgUGiEZD09ULre3OXGxRwDdcX63IUNOSdhEcJdWwLZ50GBaRbZGm9KFLfbpSUyyMNzXFZbtcNfNkRwG8wQV6bfxlM9VA/eiwqBeaxMW5arszQJWbcQSZk1WSubL0QUUpRWbP5YQFPmXz1/lm2ihdDD6uagMIjIqhHwukWr+WMDVmjIzAR4TGoQHwjDlpLHLIp74lDkYb9Ms73j7Oe/f//o6NP30Vl8QJqUj4n9r41HOt8T4psbKMOuEIT3C8UcbZRu+BDbK64ui8M3h5A79gE06bKCYLm+CbvEvzRLSCDJEbmUqF68KxQubM+OQXxNiYQ8jVn/TWaOjWH24DiCh0LrATVy6NzGpqGnNoJN8rKXDk4rcd9uRKcFCGp3UMsLo8dft7XM3/4kAm+eHKMkNvG3cilFyxEbOj+uSbTM8+NECJm4ShqqV2W3ObTM=
